### ISSUE TITLE
php artisan make:admintheme error looking for routes.php

### ISSUE THREAD

**Issue by ghost** [syahzul/admin-theme#2]
when I run php artisan make:admintheme it crashes on trying to find routes.php

[ErrorException]
file_get_contents(...../app/Http/routes.php) : Failed to open stream: No such file or directory

When I check in this directory there is indeed no routes.php
However I do have a /routes directory with 3 php files
api.php
console.php
web.php

**Comment by syahzul** [comment]
Hi,

I've updated the package to support Laravel 5.3.

Thank you.
